import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillTwitterCircle,
  AiFillInstagram,
  AiFillPhone,
} from 'react-icons/ai';
import Image from 'next/legacy/image';
import profilePic from '../public/profile-pic.jpeg';
import web1 from '../public/web1.jpeg';
import web2 from '../public/web2.jpeg';
import web3 from '../public/web3.jpeg';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Ezequiel Santalla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 mid:px-20 lg:px-40 dark:bg-gray-800">
        <nav className="py-10 mb-5 flex justify-between">
          <h1 className="text-xl font-bold text-gray-800 dark:text-gray-200">My Portfolio</h1>
          <ul className="flex items-center">
            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-gray-300"/></li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:text-gray-100" href="">Resume</a></li>
          </ul>
        </nav>

        <section className="text-center p-2">
          <h2 className="text-4xl py-1 text-teal-500 font-medium md:text-5xl">Ezequiel Santalla</h2>
          <h3 className="text-xl py-2 md:text-2xl dark:text-gray-300">Developer and Designer</h3>
          <p className="text-md py-5 leading-8 text-gray-600 md:text-lg max-w-md mx-auto dark:text-gray-400">Programming and new technologies enthusiast. Join me down below and take a look of my projects!</p>
        </section>
        <section className="text-4xl flex justify-center gap-16 py-2 text-gray-600 dark:text-gray-400">
          <AiFillLinkedin />
          <AiFillGithub />
          <AiFillTwitterCircle />
          <AiFillInstagram />
          <AiFillPhone />
        </section>
        <section className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-8 overflow-hidden">
          <Image src={profilePic} layout="fill" objectFit="cover" alt="Profile pic" />
        </section>

        <section>
          <div className="p-8">
            <h3 className="text-2xl py-2 dark:text-gray-300">About Me</h3>
            <p className="text-md py-3 leading-8 text-gray-600 dark:text-gray-400">Programmer specialized in <span className="text-teal-500 font-medium">front-end</span> development with technologies such as HTML, JavaScript, Next.js, React.js, and Tailwind CSS. I created <span className="text-teal-500 font-medium">3 projects</span> with these and other technologies and I keep learning every day in this huge world.</p>
          </div>
        </section>

        <section>
          <div className="p-8">
            <h3 className="text-2xl dark:text-gray-300">Portfolio</h3>
          </div>
          <div className="relative text-center mx-auto md:flex gap-10">
            <div className="py-3 mb-8 shadow-xl rounded-lg bg-gray-300 dark:bg-gray-700">
              <Image src={web1} alt="Tennis Club" />
              <h4 className="text-xl font-medium pt-10 pb-2 text-teal-500">Tennis Club</h4>
              <p className="text-md text-gray-600 pt-1 pb-6 dark:text-gray-400">HTML | SASS | Bootstrap</p>
            </div>
            <div className="py-3 mb-8 shadow-xl rounded-lg bg-gray-300 dark:bg-gray-700">
              <Image src={web2} alt="Bookstore" />
              <h4 className="text-xl font-medium pt-6 pb-2 text-teal-500">Bookstore</h4>
              <p className="text-md text-gray-600 pt-1 pb-6 dark:text-gray-400">HTML | SASS | JavaScript | Bootstrap</p>
            </div>
            <div className="py-3 mb-8 shadow-xl rounded-lg bg-gray-300 dark:bg-gray-700">
              <Image src={web3} alt="Weather App" />
              <h4 className="text-xl font-medium py-2 text-teal-500">Weather App</h4>
              <p className="text-md text-gray-600 pt-1 pb-6 dark:text-gray-400">HTML | CSS | JavaScript | React</p>
            </div>
          </div>
        </section>

        <footer>
          <p className="text-sm text-gray-600 pl-6 pb-5 dark:text-gray-400">Copyright © 2023 All Rights Reserved by Ezequiel Santalla</p>
        </footer>
      </main>
    </div>
  )
};
